version: '3.8'

services:

  postgres:
    container_name: ms_pg_sql
    image: postgres:alpine3.17
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data
      PGPORT: 5433
    ports:
      - "5433:5433"
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./initdb.d:/docker-entrypoint-initdb.d
    networks:
      - e-commerce-net

  mongodb:
    container_name: ms_mongo
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: customer_db
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - '27017:27017'
    volumes:
      - mongo:/data/db

  mongo-express:
    container_name: ms_mongo_express
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    links:
      - mongodb

  mail-dev:
    container_name: ms_mail_dev
    image: maildev/maildev
    ports:
      - '1080:1080'
      - '1025:1025'
  zookeeper:
    image: 'confluentinc/cp-zookeeper:latest'
    container_name: zookeeper
    ports:
      - '22181:2181'
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - e-commerce-net

  kafka:
    image: 'confluentinc/cp-kafka:latest'
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    networks:
      - e-commerce-net
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin:2.23
    restart: always
    ports:
      - '9411:9411'
    networks:
      - e-commerce-net

  redis:
    image: redis:alpine3.17
    restart: always
    ports:
      - "6379:6379"
    networks:
      - e-commerce-net

  keycloak:
    container_name: keycloak_ms
    image: quay.io/keycloak/keycloak:24.0.2
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME_PORT: 9696
    command:
      - "start-dev"
    ports:
      - '9696:8080'
    networks:
      - e-commerce-net

volumes:
  postgres:
  pgadmin:
  mongo:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local

networks:
  e-commerce-net:
    driver: bridge